#Version is defined of docker-compose that will be used but not necessary.
version: '3'
#From here we can define all the configuration for our container.
services:
#Define the name of the container and on this level we can define the multiple containers.
  node-app:
#Build command to build the container here . is there as dockerfile is ther in the same directory.
    build: .
#Defining ports which we want to expose and mutiple ports can be exposed in the list format.    
    ports:
      - 5000:5000
#Define volumes bind mount volume and the anonymous volumes      
    volumes:
      - ./:/app
      - /app/node_modules
#Environment variable are defined below and after that .env file can also be used like below.      
    environment:
      - PORT=5000
    # env_file:
    #   - ./.env     
  